export const galleryTeam = [
    {
        id:  1,
        name:  "Орест Михальчук",
        photoPreview:  "./images/team/cat_340.jpg",
        photo: "./images/team/cat_960.jpg" ,
        position:  scram,
    },
    {
        id:  2,
        name:  'Константин',
        photoPreview:  "./images/team/cat_340.jpg",
        photo: "./images/team/cat_960.jpg" ,
        position:  teamlid,
    },
    {
        id:  3,
        name:  'Євген Тітов',
        photoPreview:  "./images/team/Yevgen_Titov_340.jpg",
        photo: "./images/team/Yevgen_Titov_960.jpg" ,
        position: developer ,
    },
    {
        id:  4,
        name:  'Олександр',
        photoPreview:  "./images/team/cat_340.jpg",
        photo: "./images/team/cat_960.jpg" ,
        position:  developer,
    },
    {
        id:  5,
        name:  "Сергій Максимчук",
        photoPreview:  "./images/team/cat_340.jpg",
        photo: "./images/team/cat_960.jpg" ,
        position:  developer,
    },
    {
        id:  6,
        name:  "Олексій Рузенко",
        photoPreview:  "./images/team/Aleksey_Ryzhenko_340.jpg",
        photo: "./images/team/Aleksey_Ryzhenko_960.jpg" ,
        position: developer ,
    },
    {
        id:  7,
        name:  "Руслан Тендериць",
        photoPreview:  "./images/team/Ruslan_Tenderyts_340.jpg",
        photo: "./images/team/Ruslan_Tenderyts_960.jpg" ,
        position:  developer,
    },
    {
        id:  8,
        name:  "Владислав Роханов",
        photoPreview:  "./images/team/Vladyslav_Rohalov_340.jpg",
        photo: "./images/team/Vladyslav_Rohalov_960.jpg" ,
        position:  developer,
    },
    {
        id:  9,
        name:  "Світлана Козаченко",
        photoPreview:  "./images/team/cat_340.jpg",
        photo: "./images/team/cat_960.jpg" ,
        position: developer ,
    },
    {
        id:  10,
        name:  "Володимир",
        photoPreview:  "./images/team/cat_340.jpg",
        photo: "./images/team/cat_960.jpg" ,
        position: developer ,
    },
    {
        id:  11,
        name:  "Куценко",
        photoPreview:  "./images/team/cat_340.jpg",
        photo: "./images/team/cat_960.jpg" ,
        position: developer ,
    },
    {
        id:  12,
        name:  "Вячеслав Борисов",
        photoPreview:  "./images/team/cat_340.jpg",
        photo: "./images/team/cat_960.jpg" ,
        position:  developer,
    },
    {
        id:  13,
        name:  "Юрій Гречиха",
        photoPreview:  "./images/team/cat_340.jpg",
        photo: "./images/team/cat_960.jpg" ,
        position:  developer,
    },
]