export const galleryTeam = [
    {
        id:  1,
        name:  "Orest Mykhalchuk",
        photoPreview:  "/images/team/Orest_Mykhalchuk_150.jpg",
        photo: "/images/team/Orest_Mykhalchuk_450.jpg" ,
        position:  "Scrum Master",
    },
    {
        id:  2,
        name:  'Konstantin Yevchuk',
        photoPreview:  "/images/team/Konstantin_Yevchuk_150.jpg",
        photo: "/images/team/Konstantin_Yevchuk_450.jpg" ,
        position:  "Team Lead",
    },
    {
        id:  3,
        name:  'Eugene Titov',
        photoPreview:  "/images/team/Yevgen_Titov_150.jpg",
        photo: "/images/team/Yevgen_Titov_450.jpg" ,
        position: "developer" ,
    },
    {
        id:  4,
        name:  'Olexander Yanchenko',
        photoPreview:  "/images/team/Olexander_Yanchenko_150.jpg",
        photo: "/images/team/Olexander_Yanchenko_450.jpg" ,
        position:  "developer",
    },
    {
        id:  5,
        name:  "Sergiy Maxymchuk",
        photoPreview:  "/images/team/Sergiy_Maxymchuk_150.jpg",
        photo: "/images/team/Sergiy_Maxymchuk_450.jpg" ,
        position:  "developer",
    },
    {
        id:  6,
        name:  "Alexey Ryzhenko",
        photoPreview:  "/images/team/Aleksey_Ryzhenko_150.jpg",
        photo: "/images/team/Aleksey_Ryzhenko_450.jpg" ,
        position: "developer" ,
    },
    {
        id:  7,
        name:  "Ruslan Tenderyts",
        photoPreview:  "/images/team/Ruslan_Tenderyts_150.jpg",
        photo: "/images/team/Ruslan_Tenderyts_450.jpg" ,
        position:  "developer",
    },
    {
        id:  8,
        name:  "Vladyslav Rohalov",
        photoPreview:  "/images/team/Vladyslav_Rohalov_150.jpg",
        photo: "/images/team/Vladyslav_Rohalov_450.jpg" ,
        position:  "developer",
    },
    {
        id:  9,
        name:  "Svitlana Kozachenko",
        photoPreview:  "/images/team/Svitlana_Kozachenko_150.jpg",
        photo: "/images/team/Svitlana_Kozachenko_450.jpg" ,
        position: "developer" ,
    },
    {
        id:  10,
        name:  "Volodymyr Zankevych",
        photoPreview:  "/images/team/Volodymyr_Zankevych_150.jpg",
        photo: "/images/team/Volodymyr_Zankevych_450.jpg" ,
        position: "developer" ,
    },
    {
        id:  11,
        name:  "Olexandr Kutsenko",
        photoPreview:  "/images/team/Olexandr_Kutsenko_150.jpg",
        photo: "/images/team/Olexandr_Kutsenko_450.jpg" ,
        position: "developer" ,
    },
    {
        id:  12,
        name:  "Viacheslav Borysov",
        photoPreview:  "/images/team/Viacheslav_Borysov_150.jpg",
        photo: "/images/team/Viacheslav_Borysov_450.jpg" ,
        position:  "developer",
    },
    // {
    //     id:  13,
    //     name:  "Yuriy Grechyha",
    //     photoPreview:  "/images/team/",
    //     photo: "/images/team/" ,
    //     position:  "developer",
    // },
]