export const galleryTeam = [
    {
        id:  1,
        name:  "Orest Mykhalchuk",
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position:  "Scrum Master",
    },
    {
        id:  2,
        name:  'Konstantin Yevchuk',
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position:  "Team Lead",
    },
    {
        id:  3,
        name:  'Eugene Titov',
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position: "developer" ,
    },
    {
        id:  4,
        name:  'Olexander Yanchenko',
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position:  "developer",
    },
    {
        id:  5,
        name:  "Sergiy Maxymchuk",
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position:  "developer",
    },
    {
        id:  6,
        name:  "Alexey Ryzhenko",
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position: "developer" ,
    },
    {
        id:  7,
        name:  "Ruslan Tenderyts",
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position:  "developer",
    },
    {
        id:  8,
        name:  "Vladyslav Rohalov",
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position:  "developer",
    },
    {
        id:  9,
        name:  "Svitlana Kozachenko",
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position: "developer" ,
    },
    {
        id:  10,
        name:  "Volodymyr Zankevych",
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position: "developer" ,
    },
    {
        id:  11,
        name:  "Olexandr Kutsenko",
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position: "developer" ,
    },
    {
        id:  12,
        name:  "Viacheslav Borysov",
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg" ,
        position:  "developer",
    },
    {
        id:  13,
        name:  "Yuriy Grechyha",
        photoPreview:  "../images/team/cat_340.jpg",
        photo: "../images/team/cat_960.jpg",
        position:  "developer",
    },
]